stages:
  - pack

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm -v
  - npm install
  - npm run rebuild-native

package:
  stage: pack
  script:
    - npm run pack
  artifacts:
    paths:
      - dist/YouTracker-1.0.0.dmg
  when: manual
  # only:
  #   - master
