stages:
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm -v
  - npm install
  - npm run rebuild-native

publishing:
  stage: publish
  script:
    - npm run publish
  when: manual
