stages:
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm -v
  - npm install
  - npm run rebuild-native

publishing:
  stage: publish
  script:
    - npm run publish
  when: manual
  artifacts:
    expire_in: 1 day
    paths:
      - dist/YouTracker-1.0.0.dmg
      - dist/YouTracker Setup 1.0.0.exe
      - dist/YouTracker 1.0.0.AppImage
